/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Wraps [`ckm::CkmEngine`] for use from Node.js via napi-rs. */
export declare class CkmEngineWrapper {
  /**
   * Returns the formatted topic index for terminal display.
   * If `tool_name` is not provided, defaults to "tool".
   */
  getTopicIndex(toolName?: string | undefined | null): string
  /** Returns human-readable content for a specific topic, or null if not found. */
  getTopicContent(topicName: string): string | null
  /**
   * Returns structured JSON for a topic or the full index.
   *
   * Pass `undefined`/`null` to get the full topic index; pass a topic name
   * to get that topic's detail or an error object.
   *
   * # Errors
   *
   * Returns an error if JSON serialization of the result fails.
   */
  getTopicJson(topicName?: string | undefined | null): string
  /**
   * Returns the raw v2 manifest as a JSON string.
   *
   * # Errors
   *
   * Returns an error if JSON serialization of the manifest fails.
   */
  getManifest(): string
  /**
   * Returns manifest statistics (metadata, counts, topic names) as JSON.
   *
   * # Errors
   *
   * Returns an error if JSON serialization of the inspect result fails.
   */
  inspect(): string
  /** Returns the number of derived topics. */
  topicsCount(): number
}

/**
 * Fluent builder for constructing valid CKM v2 manifests.
 *
 * This is the **producer** side — generators use this to build manifests
 * with type safety instead of hand-rolling JSON.
 */
export declare class CkmManifestBuilderWrapper {
  /** Creates a new builder with project name and language. */
  constructor(project: string, language: string)
  /** Sets the generator name (e.g., "forge-ts@1.0.0"). */
  generator(generator: string): this
  /** Sets the source repository URL. */
  sourceUrl(url: string): this
  /** Adds a concept. */
  addConcept(name: string, slug: string, what: string, tags: Array<string>): this
  /** Adds a property to a concept by slug. */
  addConceptProperty(conceptSlug: string, name: string, canonicalType: string, description: string, required: boolean, defaultValue?: string | undefined | null): this
  /** Adds an operation with tags. */
  addOperation(name: string, what: string, tags: Array<string>): this
  /** Adds an input to an operation. */
  addOperationInput(opName: string, paramName: string, canonicalType: string, required: boolean, description: string): this
  /** Adds a constraint. */
  addConstraint(rule: string, enforcedBy: string, severity: string): this
  /** Adds a config entry. */
  addConfig(key: string, canonicalType: string, description: string, required: boolean, defaultValue?: string | undefined | null): this
  /**
   * Builds the manifest and returns it as a JSON string.
   *
   * # Errors
   *
   * Returns an error if serialization fails.
   */
  build(): string
}

/**
 * Creates a new CKM engine from a JSON string (v1 or v2 manifest).
 *
 * # Errors
 *
 * Returns an error if the input string is not valid JSON.
 */
export declare function createCkmEngine(manifestJson: string): CkmEngineWrapper

/**
 * Detects whether a manifest is v1 or v2.
 *
 * Returns 1 or 2.
 *
 * # Errors
 *
 * Returns an error if the input string is not valid JSON.
 */
export declare function detectVersion(json: string): number

/**
 * Migrates a v1 manifest to v2 format.
 *
 * Returns the v2 manifest as a JSON string.
 *
 * # Errors
 *
 * Returns an error if the input is not valid JSON or serialization fails.
 */
export declare function migrateV1ToV2(json: string): string

/**
 * Validates a manifest JSON string against the v2 schema.
 *
 * Returns a JSON string with `{ valid: boolean, errors: [...] }`.
 *
 * # Errors
 *
 * Returns an error if the input is not valid JSON or serialization fails.
 */
export declare function validateManifest(json: string): string
